# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 80
spring:
  profiles:
    # 环境 dev|test|pro
    active: dev
  application:
    name: pm
  mvc:
    throw-exception-if-no-handler-found: true
  #    static-path-pattern: /resources/**
  #    prefer-ip-address: true
  resources:
    static-locations: classpath:/static/
